{{- if gt (len .Values.ipAddressPools) 0 -}}
  {{- range $pool := $.Values.ipAddressPools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  addresses:
{{ toYaml $pool.addresses | indent 4 }}
  {{- end -}}
{{- end -}}