{{- if gt (len .Values.ipAddressPools) 0 -}}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: system-metallb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ipAddressPools:
  {{- range $pool := $.Values.ipAddressPools }}
    - {{ $pool.name }}
  {{- end -}}
{{- end -}}