apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: lldap
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}