apiVersion: v1
kind: PersistentVolume
metadata:
  name: lldap-pv
  namespace: {{ .Release.Namespace }}
  labels:
    app: lldap
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: lldap-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: lldap
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  volumeName: lldap-pv