apiVersion: v1
kind: Secret
metadata:
  name: lldap-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  lldap-jwt-secret: {{ .Values.secret.lldapJwtSecret | b64enc }}
  lldap-ldap-user-pass: {{ .Values.secret.lldapUserPass | b64enc }}
  base-dn: {{ .Values.secret.lldapBaseDn | b64enc }}