apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.secret.jwtSecret | b64enc }}
  default-admin-pass: {{ .Values.secret.defaultAdminPass | b64enc }}
  base-dn: {{ .Values.secret.baseDn | b64enc }}