{{- if .Values.traefik.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: {{ printf "Host(`%s.%s`)" .Values.traefik.subdomain .Values.traefik.domain }}
      services:
        - kind: Service
          name: {{ .Values.headlamp.fullnameOverride }}
          port: http
{{- end -}}