{{- if .Values.blocky.enabled -}}
apiVersion: blocky.io/v1
kind: DnsMapping
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
spec:
  domain: {{ printf "%s.%s" .Values.blocky.dnsMapping.subdomain .Values.blocky.dnsMapping.domain }}
  ip: {{ .Values.blocky.ip }}
{{- end -}}