{{- if .Values.blocky.enabled -}}
apiVersion: blocky.io/v1
kind: DnsMapping
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
spec:
  domain: "{{ .Values.blocky.dnsMapping.subdomain }}.{{ .Values.blocky.dnsMapping.domain }}"
  ip: {{ .Values.blocky.dnsMapping.ip }}
{{- end -}}